services:
    #    zapurlapi:
    #        image: zapurlapi
    #        container_name: zapurl.api
    #        build:
    #            context: .
    #            dockerfile: zapURL.Api/Dockerfile
    #        ports:
    #            - "5000:5000"
    #            - "5001:5001"

    zapurl.database:
        image: postgres:latest
        container_name: zapurl.database
        environment:
            - POSTGRES_DB=zapurl
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./.containers/zapurl-db:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    
    zapurl.pgadmin:
        image: elestio/pgadmin:latest
        container_name: zapurl.pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@email.com
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_LISTEN_PORT: 8080
        ports:
            - "8080:8080"
        volumes:
            - ./.containers/zapurl-pgadmin:/pgadmin4/servers.json
